language: node_js
cache: npm
matrix:
  include:
  - name: "Unit tests"
    node_js: "10.15.3"
    env: JOB=coverage
  - name: "E2E tests"
    node_js: "10.15.3"
    env: JOB=e2e
  - name: "TSLint linting"
    node_js: "10.15.3"
    env: JOB=lint
script: npm run $JOB