language: node_js
cache: npm
matrix:
  include:
  - name: "Unit tests"
    node_js: "10.15.3"
    env: JOB=test
  - name: "TSLint linting"
    node_js: "10.15.3"
    env: JOB=lint
script: npm run $JOB